Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-09, with the labels that each got.

#212 Fix dumping the cluster state
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#199 Add a env variable to allow for setting of the storage mapping
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/rundocker
Labels: approved, cncf-cla: yes, lgtm, size/S

#216 Fix restarting the cluster with BUILD_*
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#214 IPv6: Multi-cluster support and dual-stack infrastructure
  .circleci/config.yml
  README.md
  build/portforward.sh
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#219 Fix kube master hostname check for multicluster hostnames
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 IPv6: Adjust subnet prefix used for NAT64.
  .circleci/config.yml
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
