Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-08, with the labels that each got.

#166 Find free subnet and port
  .circleci/config.yml
  README.md
  build/portforward.sh
  config.sh
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#194 Use the correct context when installing kube-route
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#193 Fix unbound variable
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 New syntax for kubeadm skip checks
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#186 Missing use-context for non-multicluster
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#201 fix an issue that dind-cluster.sh join doesn't work
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#202 Addng PTP CNI plugin support
  .circleci/config.yml
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/dindnet
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 Introduce tests for IPv6, update documentation about testing/contributing
  .circleci/config.yml
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  test/shared.inc.sh
  test/test-ipv6-only.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#185 Modify bind9 (for DNS64) for K-D-C operation in a DinD environment
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/bind9/Dockerfile
  image/bind9/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#210 Enable ability to use IPVS mode for kube-proxy
  image/Dockerfile
  image/hypokube_base.dkr
Labels: approved, cncf-cla: yes, lgtm, size/XS
