Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-11, with the labels that each got.

#246 fix_start_on_mac - Do not try to use /boot on Mac
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#244 Add k8s 1.12, remove k8s 1.8
  .circleci/config.yml
  .travis.yml
  README.md
  build/buildconf.sh
  build/genfixed.sh
  build/genvars.sh
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
  image/hypokube_base.dkr
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#251 Fix k8s master (1.14)
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
  image/kubeadm.conf.1.13.tmpl
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/L

#254 Add support for containerd
  .circleci/config.yml
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
  image/Dockerfile
  image/docker.service
  image/kubeadm.conf.1.10.tmpl
  image/kubeadm.conf.1.11.tmpl
  image/kubeadm.conf.1.12.tmpl
  image/kubeadm.conf.1.13.tmpl
  image/kubelet.service
  image/rundocker
  image/snapshot
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/L

#247 Add option to allow using pre-built Kubernetes binaries
  config.sh
  dind-cluster.sh
  fixed/config-stable.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#258 Fix "DIND_K8S_BIN_DIR: unbound variable" error when running fixed scripts
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#257 Fix containerd on the worker nodes
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
