Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-07, with the labels that each got.

#167 Add jellonek to maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, size/XS

#161 Support for parallel clusters
  .circleci/config.yml
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/kubeadm.conf.tmpl
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#159 Support for IPVS CNI Plugin
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#172 Add CI for kube-router networking option
  .circleci/config.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#175 IPV6: Allow configuration of dynamic pool for NAT64.
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
