Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-06, with the labels that each got.

#142 Fix Kubernetes master build
  .circleci/config.yml
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/kubeadm.conf.tmpl
  image/wrapkubeadm
  k8s-master-fix.patch
Labels: approved, cncf-cla: yes, lgtm, size/L

#138 Replace all forward slashes with underscore.
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: cncf-cla: yes, lgtm, size/S

#143 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#144 Force MAC on pod network bridge.
  image/Dockerfile
  image/dindnet
Labels: approved, cncf-cla: yes, lgtm, size/S

#148 IPv6: Allow AAAA record use
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#150 Add an extra space in sha1sum to work with alpine's sha1sum
  Dockerfile
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 Make feature-gates and any extra args customizable
  config.sh
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/kubeadm.conf.tmpl
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/L

#151 Adding a default config.sh for stable branch
  fixed/config-stable.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
