Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-10, with the labels that each got.

#226 Fix issue with kubeadm 1.13
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/kubeadm.conf.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#229 Update source url in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 Phase 2: Dual-stack support.
  .circleci/config.yml
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
  image/Dockerfile
  image/dindnet
  image/node-info
  test/shared.inc.sh
  test/test-net-connectivity.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#240 Pin kube-router to fixed version
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#238 Install CNI_PLUGIN="weave" via cloud.weave.works
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.8.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
