Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2018-12, with the labels that each got.

#256 Update dind-cluster scripts to install calico v3.3
  README.md
  dind-cluster.sh
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.9.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 Use containerd-1.2.1
  image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#275 Re-populate fixed/ from 0.1.0 release
  fixed/dind-cluster-stable.sh
  fixed/dind-cluster-v1.10.sh
  fixed/dind-cluster-v1.11.sh
  fixed/dind-cluster-v1.12.sh
  fixed/dind-cluster-v1.13.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#271 Fix custom-docker-opts
  image/Dockerfile
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/XS
