Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2019-03, with the labels that each got.

#286 Don't disable kubelet cgroup handling unnecessarily
  image/wrapkubeadm
Labels: approved, cncf-cla: yes, lgtm, size/S

#285 Always build kubectl when building k8s from source
  dind-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#293 Fix compatibility with current master (1.15-alpha.0)
  dind-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Add SKIP_DASHBOARD flag that allows to deploy dashboard optionally
  dind-cluster.sh
  image/snapshot
Labels: approved, cncf-cla: yes, lgtm, size/L

#297 fix: dind-cluster script pattern match comparison failures
  dind-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#300 Fix the test_src_master build failure
  dind-cluster.sh
  image/snapshot
Labels: approved, cncf-cla: yes, lgtm, size/M

#296 Allow nodes to join custom network(s) during cluster launch
  dind-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
