Repository kubernetes-sigs/kubeadm-dind-cluster, pull requests merged in 2019-07, with the labels that each got.

#312 Adding support for version 1.15
  .circleci/config.yml
  .gitignore
  .travis.yml
  README.md
  build/buildconf.sh
  build/genfixed.sh
  build/genvars.sh
  build/update-test-matrix.sh
  config.sh
  dind-cluster.sh
  image/kubelet.service
  image/wrapkubeadm
  test.sh
  test/test-net-connectivity.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#316 Bugfix/fix dind image readme
  README.md
Labels: approved, cncf-cla: yes, size/XS

#315 Add pause/unpause options
  dind-cluster.sh
Labels: cncf-cla: yes, size/M

#313 Fixing linuxkit detection on the latest versions of Docker for Mac
  dind-cluster.sh
  test/test-multiple-clusters.sh
Labels: cncf-cla: yes, size/S

#308 Update example to release 0.2.0 and Kubernetes 1.14
  README.md
Labels: cncf-cla: yes, size/S
